import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Upload,MousePointer2,Scissors,Copy,Clipboard,Undo2,Redo2,Download,MessageSquare,Layers3,ZoomIn,ZoomOut,RotateCw,Trash2,Sparkles,RefreshCw,Newspaper,Settings,Move}from'lucide-react';
import'./styles.css';

const VERSION='0.4.0',REPO='DSouLzz/Bildprojekt';
const CHANGELOG=[{version:'0.4.0',date:'7 sep 2026',items:['Stabilare AI-bildredigering med GPT-Image-2.','AI-resultat kan ångras/göras om.','Förbättrade verktyg för lager: flytta, rotera och radera.','Tydligare felmeddelanden och versionskontroll.']},{version:'0.3.0',date:'7 sep 2026',items:['Desktopapp med GitHub AutoUpdate.','OpenAI-baserad AI-bildredigering via ChatGPT-panelen.','API-nyckeln lagras krypterad av desktopappen.']},{version:'0.2.0',date:'7 sep 2026',items:['Markeringsruta för klipp/kopiera.','Klistra in som flyttbart lager.','Lager, ångra/gör om och export.']}];

function App(){
 const fileRef=useRef(),stageRef=useRef();
 const[image,setImage]=useState(null),[layers,setLayers]=useState([]),[clipboard,setClipboard]=useState(null);
 const[tool,setTool]=useState('select'),[selection,setSelection]=useState(null),[drag,setDrag]=useState(null),[history,setHistory]=useState([]),[future,setFuture]=useState([]),[zoom,setZoom]=useState(1);
 const[news,setNews]=useState(true),[update,setUpdate]=useState('Kontrollerar uppdateringar…'),[prompt,setPrompt]=useState('');
 const[chat,setChat]=useState([{role:'assistant',text:'Hej! Ladda upp en bild och skriv vad du vill ändra. Exempel: “ta bort bakgrunden” eller “gör himlen blå”.'}]);
 const[keySet,setKeySet]=useState(false),[settings,setSettings]=useState(false),[apiKey,setApiKey]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{checkRelease();if(window.api?.openai)window.api.openai.hasKey().then(setKeySet);if(window.api?.updater){window.api.updater.onAvailable(()=>setUpdate('En ny desktopversion laddas ner i bakgrunden.'));window.api.updater.onDownloaded(()=>setUpdate('Ny version är klar och installeras när programmet startas om.'));window.api.updater.onError?.(m=>setUpdate('Uppdateringsfel: '+m));}},[]);
 async function checkRelease(){try{const r=await fetch(`https://api.github.com/repos/${REPO}/releases/latest`,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok){setUpdate('Ingen publicerad GitHub Release ännu.');return}const d=await r.json(),remote=(d.tag_name||'').replace(/^v/,'');setUpdate(remote&&remote!==VERSION?`Ny version ${d.tag_name} finns.`:'Du har senaste versionen.')}catch{setUpdate('Kunde inte kontrollera GitHub Releases just nu.')}}
 function load(file){if(!file?.type?.startsWith('image/'))return;const url=URL.createObjectURL(file),im=new Image();im.onload=()=>{setImage({url,im});setLayers([]);setSelection(null);setHistory([]);setFuture([])};im.src=url}
 function point(e){const r=stageRef.current.getBoundingClientRect();return{x:(e.clientX-r.left)/zoom,y:(e.clientY-r.top)/zoom}}
 function snapshot(){return layers.map(x=>({...x}))}
 function commit(next){setHistory(h=>[...h,snapshot()]);setFuture([]);setLayers(next)}
 function start(e){const p=point(e);if(tool==='select'||tool==='move'){const hit=[...layers].reverse().find(o=>p.x>=o.x&&p.x<=o.x+o.w&&p.y>=o.y&&p.y<=o.y+o.h);if(hit)setDrag({id:hit.id,dx:p.x-hit.x,dy:p.y-hit.y});return}if((tool==='cut'||tool==='copy')&&image)setSelection({x:p.x,y:p.y,w:0,h:0})}
 function move(e){const p=point(e);if(drag){setLayers(ls=>ls.map(o=>o.id===drag.id?{...o,x:p.x-drag.dx,y:p.y-drag.dy}:o));return}if(selection)setSelection(s=>({...s,w:p.x-s.x,h:p.y-s.y}))}
 function end(){if(drag){setHistory(h=>[...h,snapshot()]);setFuture([]);setDrag(null);return}if(selection&&Math.abs(selection.w)>4&&Math.abs(selection.h)>4)extract()}
 function extract(){const s=selection;let x=Math.min(s.x,s.x+s.w),y=Math.min(s.y,s.y+s.h),w=Math.abs(s.w),h=Math.abs(s.h);x=Math.max(0,Math.min(x,image.im.naturalWidth));y=Math.max(0,Math.min(y,image.im.naturalHeight));w=Math.min(w,image.im.naturalWidth-x);h=Math.min(h,image.im.naturalHeight-y);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(image.im,x,y,w,h,0,0,w,h);c.toBlob(blob=>{const url=URL.createObjectURL(blob);setClipboard({url,w,h});if(tool==='cut')commit([]);setSelection(null);setTool('select')})}
 function paste(){if(!clipboard)return;commit([...layers,{id:crypto.randomUUID(),url:clipboard.url,x:30+layers.length*18,y:30+layers.length*18,w:clipboard.w,h:clipboard.h,rot:0}])}
 function undo(){if(!history.length)return;setFuture(f=>[snapshot(),...f]);setLayers(history.at(-1));setHistory(h=>h.slice(0,-1))}
 function redo(){if(!future.length)return;setHistory(h=>[...h,snapshot()]);setLayers(future[0]);setFuture(f=>f.slice(1))}
 function rotate(id){commit(layers.map(o=>o.id===id?{...o,rot:o.rot+90}:o))}
 function remove(id){commit(layers.filter(o=>o.id!==id))}
 function exportPng(){if(!image)return;const c=document.createElement('canvas');c.width=image.im.naturalWidth;c.height=image.im.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(image.im,0,0);let left=layers.length;if(!left)return download(c);layers.forEach(o=>{const im=new Image();im.onload=()=>{ctx.save();ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate(o.rot*Math.PI/180);ctx.drawImage(im,-o.w/2,-o.h/2,o.w,o.h);ctx.restore();if(--left===0)download(c)};im.src=o.url})}
 function download(c){const a=document.createElement('a');a.download='mitt-bild-projekt.png';a.href=c.toDataURL('image/png');a.click()}
 async function toDataUrl(url){const b=await fetch(url).then(r=>r.blob());return await new Promise(res=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.readAsDataURL(b)})}
 async function send(){const t=prompt.trim();if(!t||busy)return;if(!image||!window.api?.openai){setChat(c=>[...c,{role:'user',text:t},{role:'assistant',text:'AI-redigering kräver desktopversionen. Kör npm run dist för att bygga den.'}]);setPrompt('');return}setChat(c=>[...c,{role:'user',text:t},{role:'assistant',text:'Redigerar bilden…'}]);setBusy(true);try{const data=await toDataUrl(image.url);const out=await window.api.openai.edit({imageDataUrl:data,prompt:t});const im=new Image();im.onload=()=>{setHistory(h=>[...h,layers.map(x=>({...x}))]);setFuture([]);setLayers([]);setImage({url:out,im})};im.src=out;setChat(c=>[...c,{role:'assistant',text:'Klart. AI-resultatet är nu aktivt och kan ångras med Ångra.'}])}catch(e){setChat(c=>[...c,{role:'assistant',text:'AI-fel: '+(e?.message||e)}])}finally{setBusy(false);setPrompt('')}}
 async function saveKey(){if(!window.api?.openai)return;await window.api.openai.setKey(apiKey);setKeySet(true);setApiKey('');setSettings(false)}
 return <div className='app'>
 <header><div className='brand'><div className='logo'><Sparkles/></div><div><b>Mitt bild projekt</b><small>v{VERSION}</small></div></div><div className='actions'><button onClick={undo} disabled={!history.length}><Undo2/>Ångra</button><button onClick={redo} disabled={!future.length}><Redo2/>Gör om</button><button className='dark' onClick={exportPng} disabled={!image}><Download/>Exportera</button><button onClick={()=>setSettings(true)}><Settings/></button><button onClick={()=>{setNews(true);checkRelease()}}><RefreshCw/></button></div></header>
 <main><aside className='tools'><button className={tool==='select'?'on':''} onClick={()=>setTool('select')} title='Markera/flytta'><MousePointer2/></button><button className={tool==='cut'?'on':''} onClick={()=>setTool('cut')} title='Klipp ut'><Scissors/></button><button className={tool==='copy'?'on':''} onClick={()=>setTool('copy')} title='Kopiera'><Copy/></button><button onClick={paste} disabled={!clipboard} title='Klistra in'><Clipboard/></button><hr/><button className={tool==='move'?'on':''} onClick={()=>setTool('move')} title='Flytta lager'><Move/></button><button title='Välj ett lager för att rotera det' onClick={()=>layers[0]&&rotate(layers[0].id)}><RotateCw/></button><button title='Radera översta lagret' onClick={()=>layers[0]&&remove(layers[0].id)}><Trash2/></button></aside>
 <section className='canvas' onDrop={e=>{e.preventDefault();load(e.dataTransfer.files?.[0])}} onDragOver={e=>e.preventDefault()}>{!image?<div className='drop' onClick={()=>fileRef.current?.click()}><Upload/><h2>Dra en bild hit</h2><p>eller klicka för att välja en bild</p><button className='dark'>Välj bild</button><input ref={fileRef} hidden type='file' accept='image/*' onChange={e=>load(e.target.files?.[0])}/></div>:<div className='stageWrap'><div className='zoom'><button onClick={()=>setZoom(z=>Math.max(.25,z-.1))}><ZoomOut/></button>{Math.round(zoom*100)}%<button onClick={()=>setZoom(z=>Math.min(3,z+.1))}><ZoomIn/></button></div><div ref={stageRef} className='stage' style={{transform:`scale(${zoom})`}} onMouseDown={start} onMouseMove={move} onMouseUp={end}><img className='base' src={image.url} draggable='false'/>{layers.map(o=><img key={o.id} className='obj' src={o.url} style={{left:o.x,top:o.y,width:o.w,height:o.h,transform:`rotate(${o.rot}deg)`}} draggable='false' onMouseDown={e=>{e.stopPropagation();setTool('select');start(e)}}/>)}{selection&&<div className='selection' style={{left:Math.min(selection.x,selection.x+selection.w),top:Math.min(selection.y,selection.y+selection.h),width:Math.abs(selection.w),height:Math.abs(selection.h)}}/>}</div></div>}</section>
 <aside className='right'><h3><Layers3/>Lager</h3><div className='layer'><img src={image?.url||''}/><span>{image?'Bakgrund':'Ingen bild'}</span></div>{layers.map(o=><div className='layer' key={o.id}><img src={o.url}/><span>Utklipp</span><button onClick={()=>rotate(o.id)}><RotateCw/></button><button onClick={()=>remove(o.id)}><Trash2/></button></div>)}<h3><MessageSquare/>ChatGPT {busy&&'· arbetar…'}</h3><div className='chat'>{chat.map((m,i)=><div className={m.role} key={i}>{m.text}</div>)}</div><div className='input'><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder='T.ex. “ta bort bakgrunden”'/><button className='dark' onClick={send} disabled={busy||!prompt.trim()}>Skicka</button></div></aside></main>
 {news&&<div className='modal'><div className='modalBox'><div className='modalHead'><div><Newspaper/><h2>Vad är nytt?</h2></div><button onClick={()=>setNews(false)}>×</button></div><p className='status'>{update}</p>{CHANGELOG.map(n=><section key={n.version}><b>v{n.version} · {n.date}</b><ul>{n.items.map(x=><li key={x}>{x}</li>)}</ul></section>)}<button className='dark wide' onClick={()=>setNews(false)}>Fortsätt</button></div></div>}
 {settings&&<div className='modal'><div className='modalBox'><div className='modalHead'><div><Settings/><h2>Inställningar</h2></div><button onClick={()=>setSettings(false)}>×</button></div><p>OpenAI API-nyckel: {keySet?'sparad krypterat':'saknas'}</p><input className='keyInput' type='password' value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder='sk-…'/><button className='dark wide' onClick={saveKey} disabled={!apiKey.trim()}>Spara API-nyckel</button><p className='hint'>Nyckeln sparas lokalt av desktopappen och skickas inte till GitHub.</p></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
